### ISSUE TITLE
Your input needed

### ISSUE THREAD

**Issue by tad1073-zz** [tiiiecherle/linux_scripts#1]
I was wondering if you could take a look at my nftables rules and help me simplifie it.

https://github.com/tad1073/nftables/blob/master/rules-2-share.nft

**Comment by tiiiecherle** [comment]
I'm sorry the link you send is no longer working.

**Comment by tad1073-zz** [comment]
Here's the updated version. Other than using define and include, how can I
simplify it?
https://github.com/tad1073/nftables/blob/master/InetShare.nft

**Comment by tiiiecherle** [comment]
I don't know if it needs simplification if it works. You could define some variables for redundant occurrences of ports or functions for redundant code.
